DROP PROCEDURE IF EXISTS category_move;
DROP PROCEDURE IF EXISTS category_delete;
DROP PROCEDURE IF EXISTS category_add;
DROP PROCEDURE IF EXISTS category_setup;
DROP PROCEDURE IF EXISTS category_visualize;
